codecov:
  branch: develop

  max_report_age: off
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status: # Used when blocking PRs that don't meet a particular coverage threshold.
    patch: on
    project: on


parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

