name: Code Coverage

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  codecov:
    name: CodeCov report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['5.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set current commit sha as env var
        run: echo COMMIT_SHA=$(git rev-parse HEAD) >> $GITHUB_ENV
      - name: Test code
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Upload code
        run:
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}