name: Docker image

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker image build
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker build
      working-directory: ./backend
      run: docker build -t docker.pkg.github.com/SimCorp/nats-topology-visualiser/backend .
    - name: Docker login
      run: docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Docker push
      run: docker push docker.pkg.github.com/SimCorp/nats-topology-visualiser/backend