name: .Net Unit test

# This workflow will run with these triggers
on:
  # Trigger on pull requests to develop
  pull_request:
    branches: [ develop ]
  # Manual trigger
  workflow_dispatch:

# A workflow run is made up of one or more jobs.
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      working-directory:  ./tests/backend.Tests
      run: |
        docker build -t test-image:latest .
        docker run -d --network="host" -p 4222:4222 test-image:latest
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build dotnet project
      run: dotnet build --no-restore
    - name: Run dotnet tests
      working-directory: ./tests/backend.Tests
      run: dotnet test --no-build --verbosity normal
