name: .Net Unit test

# This workflow will run with these triggers
on:
  # Trigger on pull requests to develop
  pull_request:
    branches: [ develop ]
  # Manual trigger
  workflow_dispatch:

# A workflow run is made up of one or more jobs.
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend
    - name: Build dotnet project
      run: dotnet build --no-restore
      working-directory: ./backend
    - name: Run dotnet tests
      working-directory: ./backend/backend.Tests
      run: dotnet test --no-build --verbosity normal
