name: Example

on:
  pull_request:

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Set up and run node.js
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [10.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test